
/*
 * Copyright (c) 2022 HWFLY
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __STATUSCODE_H_
#define __STATUSCODE_H_

enum STATUSCODE
{
	OK = 0, // generic ok

	ERR_UNKNOWN_DEVICE = 0xBAD00107,
	ERR_ADC_WAIT_TIMEOUT = 0xBAD00122,

	ERR_CONFIG_MAGIC_MISMATCH = 0xBAD0010B,
	ERR_CONFIG_TABLE_FULL = 0xBAD00125,
	ERR_CONFIG_RESET_FAIL = 0xBAD00000,
	OK_CONFIG = 0x900D0007,
	OK_CONFIG_RESET = 0x900D0002,

	ERR_FLASH_ERASE_FAIL = 0xBAD00109,
	ERR_FLASH_WRITE_FAIL = 0xBAD0010A,
	ERR_FLASH_PAYLOAD_FAIL = 0xBAD0010C,
	ERR_FPGA_STATUS_FAIL = 0xBAD00004,
	OK_FLASH_SUCCESS = 0x900D0008,

	OK_FPGA_RESET = 0x900D0000,

	// Glitch error codes
	ERR_GLITCH_TOO_MANY_ATTEMPTS = 0xBAD00124,
	ERR_GLITCH_NO_EMMC_COMM = 0xBAD00108,
	OK_GLITCH_SUCCESS = 0x900D0006,

	// MMC error codes
	ERR_MMC_GO_IDLE_FAILED = 0xBAD0010D,
	ERR_MMC_SEND_OP_COND_FAILED = 0xBAD00110,
	ERR_MMC_SEND_CID_FAILED = 0xBAD00111,
	ERR_MMC_SET_RELATIVE_ADDR_FAILED = 0xBAD00112,
	ERR_MMC_STATE_UNEXPECTED_NOT_IDENT = 0xBAD00113,
	ERR_MMC_SEND_CSD_FAILED = 0xBAD00114,
	ERR_MMC_SELECT_CARD_FAILED = 0xBAD00115,
	ERR_MMC_STATE_NOT_IDENT_OR_READY = 0xBAD00116,
	ERR_MMC_SEND_STATUS_FAILED = 0xBAD00117,
	ERR_MMC_STATE_UNEXPECTED_NOT_TRAN1 = 0xBAD00118,
	ERR_MMC_SET_BLOCKLEN_FAILED = 0xBAD00119,
	ERR_MMC_STATE_UNEXPECTED_NOT_TRAN2 = 0xBAD0011A,
	ERR_MMC_SWITCH_FAILED = 0xBAD0011B,
	ERR_MMC_STATE_UNEXPECTED_NOT_TRAN3 = 0xBAD0011C,
	ERR_MMC_READ_SINGLE_BLOCK_FAILED = 0xBAD0011D,
	ERR_MMC_STATE_UNEXPECTED_NOT_TRAN4 = 0xBAD0011E,
	ERR_MMC_WRITE_SINGLE_BLOCK_FAILED = 0xBAD00120,
	ERR_MMC_STATE_UNEXPECTED_NOT_TRAN5 = 0xBAD00121,
};


#endif